services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - back-network

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes 
    volumes:
      - redis_data:/data
    networks:
      - back-network

  wordpress:
    image: wordpress:latest
    restart: always
    depends_on:
      - db
      - redis
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - front-network
      - back-network
    deploy:
      replicas: 2

  proxy:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/wp-nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8083:80
    depends_on:
      - wordpress
    networks:
      - front-network

networks:
  front-network:
    driver: bridge
  back-network:
    driver: bridge

volumes:
  db_data:
  redis_data:
  wordpress_data:


      