services:
  my_app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '3000'
    deploy:
      replicas: 4
    restart: always
    environment:
      - PING_LISTEN_PORT=3000
    networks:
      - front-network
    volumes:
      - db_data:/app/bdd.db
  
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8082:80
    depends_on:
      - my_app
    networks:
      - front-network

networks:
  front-network:
    driver: bridge

volumes:
  db_data: