FROM node:22-alpine AS builder

RUN addgroup -S myuser && adduser -S myuser -G myuser
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
WORKDIR /app
RUN corepack enable
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
COPY tsconfig.json ./ 
COPY src ./src
RUN pnpm run build

FROM node:22-alpine AS runner
RUN addgroup -S myuser && adduser -S myuser -G myuser
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
RUN chown -R myuser:myuser /app
USER myuser
EXPOSE 3000
CMD ["node", "dist/server.js"]